all:
	gcc -c cg2d.c
	gcc exemplo5.c -o exemplo5 cg2d.o -lm -lX11
	gcc exemplo6.c -o exemplo6 cg2d.o -lm -lX11
	gcc exemplo7.c -o exemplo7 cg2d.o -lm -lX11
	gcc exemplo8.c -o exemplo8 cg2d.o -lm -lX11
	
